apiVersion: v1
kind: ConfigMap
metadata:
  name: kimai-app-configmap
data:
  # property-like keys; each key maps to a simple value
  # ADMINMAIL: "pradeepbo@cybage.com"
  TRUSTED_HOSTS: "localhost,127.0.0.1,3.226.251.133"
  # DATABASE_URL: "mysql://root:Pradeep221899@172.31.69.150:3306/kimai"
